spring.application.name=demo
server.port=9099
spring.datasource.url=jdbc:mysql://localhost:3306/emergency_db
spring.datasource.username=root
spring.datasource.password=170275

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true